/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EditaisRouteImport } from './routes/editais'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreparatorioIndexRouteImport } from './routes/preparatorio.index'
import { Route as ConcursoIndexRouteImport } from './routes/concurso.index'
import { Route as PreparatorioFaculdadeRouteImport } from './routes/preparatorio.$faculdade'
import { Route as LivroIdRouteImport } from './routes/livro.$id'
import { Route as ConcursoMinisterioRouteImport } from './routes/concurso.$ministerio'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PreparatorioFaculdadeCursoRouteImport } from './routes/preparatorio.$faculdade_.$curso'
import { Route as ConcursoMinisterioSectorRouteImport } from './routes/concurso.$ministerio_.$sector'
import { Route as SimuladoKindTrackSectorRouteImport } from './routes/simulado.$kind.$track.$sector'
import { Route as ApiPublicBookCoverFileRouteImport } from './routes/api/public/book-cover.$file'
import { Route as AulaKindTrackSectorModuleLessonRouteImport } from './routes/aula.$kind.$track.$sector.$module.$lesson'

const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisRoute = EditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparatorioIndexRoute = PreparatorioIndexRouteImport.update({
  id: '/preparatorio/',
  path: '/preparatorio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursoIndexRoute = ConcursoIndexRouteImport.update({
  id: '/concurso/',
  path: '/concurso/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparatorioFaculdadeRoute = PreparatorioFaculdadeRouteImport.update({
  id: '/preparatorio/$faculdade',
  path: '/preparatorio/$faculdade',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroIdRoute = LivroIdRouteImport.update({
  id: '/livro/$id',
  path: '/livro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursoMinisterioRoute = ConcursoMinisterioRouteImport.update({
  id: '/concurso/$ministerio',
  path: '/concurso/$ministerio',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparatorioFaculdadeCursoRoute =
  PreparatorioFaculdadeCursoRouteImport.update({
    id: '/preparatorio/$faculdade_/$curso',
    path: '/preparatorio/$faculdade/$curso',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConcursoMinisterioSectorRoute =
  ConcursoMinisterioSectorRouteImport.update({
    id: '/concurso/$ministerio_/$sector',
    path: '/concurso/$ministerio/$sector',
    getParentRoute: () => rootRouteImport,
  } as any)
const SimuladoKindTrackSectorRoute = SimuladoKindTrackSectorRouteImport.update({
  id: '/simulado/$kind/$track/$sector',
  path: '/simulado/$kind/$track/$sector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookCoverFileRoute = ApiPublicBookCoverFileRouteImport.update({
  id: '/api/public/book-cover/$file',
  path: '/api/public/book-cover/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaKindTrackSectorModuleLessonRoute =
  AulaKindTrackSectorModuleLessonRouteImport.update({
    id: '/aula/$kind/$track/$sector/$module/$lesson',
    path: '/aula/$kind/$track/$sector/$module/$lesson',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/editais': typeof EditaisRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/revisao': typeof RevisaoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/concurso/$ministerio': typeof ConcursoMinisterioRoute
  '/livro/$id': typeof LivroIdRoute
  '/preparatorio/$faculdade': typeof PreparatorioFaculdadeRoute
  '/concurso/': typeof ConcursoIndexRoute
  '/preparatorio/': typeof PreparatorioIndexRoute
  '/concurso/$ministerio/$sector': typeof ConcursoMinisterioSectorRoute
  '/preparatorio/$faculdade/$curso': typeof PreparatorioFaculdadeCursoRoute
  '/api/public/book-cover/$file': typeof ApiPublicBookCoverFileRoute
  '/simulado/$kind/$track/$sector': typeof SimuladoKindTrackSectorRoute
  '/aula/$kind/$track/$sector/$module/$lesson': typeof AulaKindTrackSectorModuleLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/editais': typeof EditaisRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/revisao': typeof RevisaoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/concurso/$ministerio': typeof ConcursoMinisterioRoute
  '/livro/$id': typeof LivroIdRoute
  '/preparatorio/$faculdade': typeof PreparatorioFaculdadeRoute
  '/concurso': typeof ConcursoIndexRoute
  '/preparatorio': typeof PreparatorioIndexRoute
  '/concurso/$ministerio/$sector': typeof ConcursoMinisterioSectorRoute
  '/preparatorio/$faculdade/$curso': typeof PreparatorioFaculdadeCursoRoute
  '/api/public/book-cover/$file': typeof ApiPublicBookCoverFileRoute
  '/simulado/$kind/$track/$sector': typeof SimuladoKindTrackSectorRoute
  '/aula/$kind/$track/$sector/$module/$lesson': typeof AulaKindTrackSectorModuleLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/editais': typeof EditaisRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/revisao': typeof RevisaoRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/concurso/$ministerio': typeof ConcursoMinisterioRoute
  '/livro/$id': typeof LivroIdRoute
  '/preparatorio/$faculdade': typeof PreparatorioFaculdadeRoute
  '/concurso/': typeof ConcursoIndexRoute
  '/preparatorio/': typeof PreparatorioIndexRoute
  '/concurso/$ministerio_/$sector': typeof ConcursoMinisterioSectorRoute
  '/preparatorio/$faculdade_/$curso': typeof PreparatorioFaculdadeCursoRoute
  '/api/public/book-cover/$file': typeof ApiPublicBookCoverFileRoute
  '/simulado/$kind/$track/$sector': typeof SimuladoKindTrackSectorRoute
  '/aula/$kind/$track/$sector/$module/$lesson': typeof AulaKindTrackSectorModuleLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/editais'
    | '/entrar'
    | '/painel'
    | '/revisao'
    | '/categoria/$slug'
    | '/concurso/$ministerio'
    | '/livro/$id'
    | '/preparatorio/$faculdade'
    | '/concurso/'
    | '/preparatorio/'
    | '/concurso/$ministerio/$sector'
    | '/preparatorio/$faculdade/$curso'
    | '/api/public/book-cover/$file'
    | '/simulado/$kind/$track/$sector'
    | '/aula/$kind/$track/$sector/$module/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/editais'
    | '/entrar'
    | '/painel'
    | '/revisao'
    | '/categoria/$slug'
    | '/concurso/$ministerio'
    | '/livro/$id'
    | '/preparatorio/$faculdade'
    | '/concurso'
    | '/preparatorio'
    | '/concurso/$ministerio/$sector'
    | '/preparatorio/$faculdade/$curso'
    | '/api/public/book-cover/$file'
    | '/simulado/$kind/$track/$sector'
    | '/aula/$kind/$track/$sector/$module/$lesson'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/editais'
    | '/entrar'
    | '/painel'
    | '/revisao'
    | '/categoria/$slug'
    | '/concurso/$ministerio'
    | '/livro/$id'
    | '/preparatorio/$faculdade'
    | '/concurso/'
    | '/preparatorio/'
    | '/concurso/$ministerio_/$sector'
    | '/preparatorio/$faculdade_/$curso'
    | '/api/public/book-cover/$file'
    | '/simulado/$kind/$track/$sector'
    | '/aula/$kind/$track/$sector/$module/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EditaisRoute: typeof EditaisRoute
  EntrarRoute: typeof EntrarRoute
  PainelRoute: typeof PainelRoute
  RevisaoRoute: typeof RevisaoRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ConcursoMinisterioRoute: typeof ConcursoMinisterioRoute
  LivroIdRoute: typeof LivroIdRoute
  PreparatorioFaculdadeRoute: typeof PreparatorioFaculdadeRoute
  ConcursoIndexRoute: typeof ConcursoIndexRoute
  PreparatorioIndexRoute: typeof PreparatorioIndexRoute
  ConcursoMinisterioSectorRoute: typeof ConcursoMinisterioSectorRoute
  PreparatorioFaculdadeCursoRoute: typeof PreparatorioFaculdadeCursoRoute
  ApiPublicBookCoverFileRoute: typeof ApiPublicBookCoverFileRoute
  SimuladoKindTrackSectorRoute: typeof SimuladoKindTrackSectorRoute
  AulaKindTrackSectorModuleLessonRoute: typeof AulaKindTrackSectorModuleLessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais': {
      id: '/editais'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof EditaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparatorio/': {
      id: '/preparatorio/'
      path: '/preparatorio'
      fullPath: '/preparatorio/'
      preLoaderRoute: typeof PreparatorioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurso/': {
      id: '/concurso/'
      path: '/concurso'
      fullPath: '/concurso/'
      preLoaderRoute: typeof ConcursoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparatorio/$faculdade': {
      id: '/preparatorio/$faculdade'
      path: '/preparatorio/$faculdade'
      fullPath: '/preparatorio/$faculdade'
      preLoaderRoute: typeof PreparatorioFaculdadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$id': {
      id: '/livro/$id'
      path: '/livro/$id'
      fullPath: '/livro/$id'
      preLoaderRoute: typeof LivroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurso/$ministerio': {
      id: '/concurso/$ministerio'
      path: '/concurso/$ministerio'
      fullPath: '/concurso/$ministerio'
      preLoaderRoute: typeof ConcursoMinisterioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparatorio/$faculdade_/$curso': {
      id: '/preparatorio/$faculdade_/$curso'
      path: '/preparatorio/$faculdade/$curso'
      fullPath: '/preparatorio/$faculdade/$curso'
      preLoaderRoute: typeof PreparatorioFaculdadeCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurso/$ministerio_/$sector': {
      id: '/concurso/$ministerio_/$sector'
      path: '/concurso/$ministerio/$sector'
      fullPath: '/concurso/$ministerio/$sector'
      preLoaderRoute: typeof ConcursoMinisterioSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado/$kind/$track/$sector': {
      id: '/simulado/$kind/$track/$sector'
      path: '/simulado/$kind/$track/$sector'
      fullPath: '/simulado/$kind/$track/$sector'
      preLoaderRoute: typeof SimuladoKindTrackSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book-cover/$file': {
      id: '/api/public/book-cover/$file'
      path: '/api/public/book-cover/$file'
      fullPath: '/api/public/book-cover/$file'
      preLoaderRoute: typeof ApiPublicBookCoverFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$kind/$track/$sector/$module/$lesson': {
      id: '/aula/$kind/$track/$sector/$module/$lesson'
      path: '/aula/$kind/$track/$sector/$module/$lesson'
      fullPath: '/aula/$kind/$track/$sector/$module/$lesson'
      preLoaderRoute: typeof AulaKindTrackSectorModuleLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EditaisRoute: EditaisRoute,
  EntrarRoute: EntrarRoute,
  PainelRoute: PainelRoute,
  RevisaoRoute: RevisaoRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ConcursoMinisterioRoute: ConcursoMinisterioRoute,
  LivroIdRoute: LivroIdRoute,
  PreparatorioFaculdadeRoute: PreparatorioFaculdadeRoute,
  ConcursoIndexRoute: ConcursoIndexRoute,
  PreparatorioIndexRoute: PreparatorioIndexRoute,
  ConcursoMinisterioSectorRoute: ConcursoMinisterioSectorRoute,
  PreparatorioFaculdadeCursoRoute: PreparatorioFaculdadeCursoRoute,
  ApiPublicBookCoverFileRoute: ApiPublicBookCoverFileRoute,
  SimuladoKindTrackSectorRoute: SimuladoKindTrackSectorRoute,
  AulaKindTrackSectorModuleLessonRoute: AulaKindTrackSectorModuleLessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
